config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'actualizar_valor_hh', to: 'orders#arreglar_valor_hh'

  get 'gruas/revisar_mantenciones', to: 'gruas#revisar_mantenciones',
   as: :revisar_mantenciones
  post 'gruas/analisis', to: 'gruas#analisis', as: :analisis

  get 'gruas/mantencion_realizada', to: 'gruas#mantencion_realizada', as: :mantencion_realizada

  post 'gruas/actualizar_hora_hombre', to: 'gruas#actualizar_hora_hombre', as: :actualizar_hora_hombre
  post 'gruas/horometros_iniciales', to: 'gruas#horometros_iniciales', as: :horometros_iniciales
  
  resources :ingresos do
    get 'cerrar', to: "ingresos#cerrar", as: :cerrar
    get 'completar', to: "ingresos#completar", as: :completar
  end

  resources :clientes do
    collection { post :import }
  end

  resources :repuestos do
    collection { post :import }
    post 'actualizar_atributos', to: 'repuestos#actualizar_atributos', as: :actualizar_atributos
  end
  
  resources :gruas do
    collection { post :import }
    post 'actualizar_horometro', to: 'gruas#actualizar_horometro', as: :actualizar_horometro
    post 'actualizar_cliente', to: 'gruas#actualizar_cliente', as: :actualizar_cliente
    post 'calcular_repuestos', to: 'gruas#calcular_repuestos', as: :calcular_repuestos
  	resources :orders
  end

  resources :suppliers do
  	collection { post :import }
  end

  resources :traspasos
  resources :ajustes

  #get 'importar', to: 'gruas#importar', as: :importar

  root "gruas#index"
end

app/models/repuesto.rb
class Repuesto < ApplicationRecord
	validates :codigo, uniqueness: true
	require 'csv'

   	def self.import(file)
   		CSV.foreach(file.path, headers: false) do |row|
   			if row[4]
   				pan = row[4]
   			else pan = 0
   			end

   			if row[5]
   				mov1 = row[5]
   			else mov1 = 0
   			end

   			if row[6]
   				mov2 = row[6]
   			else mov2 = 0
   			end

   			if row[7]
   				sto = row[7]
   			else sto = 0
   			end

   			if row[8]
   				sto_min = row[8]
   			else sto_min = 0
   			end

   			if row[9]
   				val = row[9]
   			else val = 0
   			end

      		Repuesto.create!(codigo: row[0], articulo: row[1], familia: row[3],
      		panol: pan, movil1: mov1, movil2: mov2, stock: sto,
      		stock_minimo: sto_min, valor: val)
    	end
   	end

	def self.agregar(lista_repuestos)
		total = 0
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			cantidad = tupla[1].to_f
			r.panol += cantidad
			r.stock += cantidad
			if tupla[2].to_f != 0
				r.valor = tupla[2].to_f
			end
			r.save
			total += cantidad*r.valor
		end
		return total
	end

	def self.agregar_faltantes(lista_repuestos)
		total = 0
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			cantidad = tupla[1].to_f
			r.panol += cantidad
			r.stock += cantidad
			r.save
			total += cantidad*r.valor
		end
		return total
	end

	def self.rebajar(lista_repuestos, equipo)
		total = 0
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			r.stock -= tupla[1].to_f
			if equipo == "Móvil 1"
				r.movil1 -= tupla[1].to_f
			elsif equipo == "Móvil 2"
				r.movil2 -= tupla[1].to_f
			elsif equipo == "Taller"
				r.taller -= tupla[1].to_f
			else
				r.panol -= tupla[1].to_f
			end
			r.save
			total += tupla[1].to_f*r.valor
		end
		return total
	end

	def self.reponer(lista_repuestos, equipo)
		"""
		Reponemos los repuestos en el caso de que OT sea eliminada
		"""
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			r.stock += tupla[1].to_f
			if equipo == "Móvil 1"
				r.movil1 += tupla[1].to_f
			elsif equipo == "Móvil 2"
				r.movil2 += tupla[1].to_f
			elsif equipo == "Central"
				r.taller += tupla[1].to_f
			else
				r.panol += tupla[1].to_f
			end
			r.save
		end
	end

	def self.traspasar(lista_repuestos, desde, hacia)
		self.bajar(lista_repuestos, desde)
		self.subir(lista_repuestos, hacia)
	end

	def self.bajar(lista_repuestos, equipo)
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			if equipo == "Móvil 1"
				r.movil1 -= tupla[1].to_f
			elsif equipo == "Móvil 2"
				r.movil2 -= tupla[1].to_f
			elsif equipo == "Taller"
				r.taller -= tupla[1].to_f
			else
				r.panol -= tupla[1].to_f
			end
			r.save
		end
	end

	def self.subir(lista_repuestos, equipo)
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			if equipo == "Móvil 1"
				r.movil1 += tupla[1].to_f
			elsif equipo == "Móvil 2"
				r.movil2 += tupla[1].to_f
			elsif equipo == "Taller"
				r.taller += tupla[1].to_f
			else
				r.panol += tupla[1].to_f
			end
			r.save
		end
	end

	def self.ajustar(lista_repuestos, sentido, equipo)
		if sentido == 'Baja'
			self.rebajar(lista_repuestos, equipo)
		else
			self.aumentar(lista_repuestos, equipo)
		end
	end

	def self.aumentar(lista_repuestos, equipo)
		lista_repuestos.each do |tupla|
			r = Repuesto.find_by(codigo: tupla[0])
			r.stock += tupla[1].to_f
			if equipo == "Móvil 1"
				r.movil1 += tupla[1].to_f
			elsif equipo == "Móvil 2"
				r.movil2 += tupla[1].to_f
			elsif equipo == "Taller"
				r.taller += tupla[1].to_f
			else
				r.panol += tupla[1].to_f
			end
			r.save
		end
	end

end

app/controllers/repuestos_controller.rb
class RepuestosController < ApplicationController
  before_action :set_repuesto, only: [:show, :edit, :update, :destroy]

  # GET /repuestos
  # GET /repuestos.json
  def index
    @q = Repuesto.search(params[:q])
    @repuestos = @q.result.order('codigo ASC')

    tipo = params[:tipo]
    if tipo == "Insumo"
      @repuestos = @repuestos.where("familia = 'Insumo'")
    elsif tipo == "Lubricante"
      @repuestos = @repuestos.where("familia = 'Lubricante'")
    elsif tipo == "Neumatico"
      @repuestos = @repuestos.where("familia = 'Neumáticos'")
    elsif tipo == "Pintura"
      @repuestos = @repuestos.where("familia = 'Pintura'")
    elsif tipo == "Repuesto"
      @repuestos = @repuestos.where("familia = 'Repuesto'")
    elsif tipo == "Seguridad"
      @repuestos = @repuestos.where("familia = 'Seguridad'")
    elsif tipo == "Faltantes"
      @repuestos = @repuestos.where("stock < stock_minimo")
    end
  end

  # GET /repuestos/1
  # GET /repuestos/1.json
  def show
  end

  # GET /repuestos/new
  def new
    @repuesto = Repuesto.new
  end

  # GET /repuestos/1/edit
  def edit
  end

  # POST /repuestos
  # POST /repuestos.json
  def create
    @repuesto = Repuesto.new(repuesto_params)

    respond_to do |format|
      if @repuesto.save
        format.html { redirect_to @repuesto, notice: 'Repuesto creado exitosamente' }
        format.json { render :show, status: :created, location: @repuesto }
      else
        format.html { render :new }
        format.json { render json: @repuesto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  # DELETE /repuestos/1
  # DELETE /repuestos/1.json
  def destroy
    @repuesto.destroy
    respond_to do |format|
      format.html { redirect_to repuestos_url, notice: 'Repuesto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Repuesto.import(params[:file])
    redirect_to repuestos_url, notice: "Repuesto(s) importado(s)"
  end


  def actualizar_atributos
    @repuesto = Repuesto.find(params[:repuesto_id])
    @nuevo_stock_minimo = params[:nuevo_stock_minimo]
    @nuevo_valor = params[:nuevo_valor]
    if @nuevo_stock_minimo != ''
      @repuesto.stock_minimo = @nuevo_stock_minimo.to_f
    end
    if @nuevo_valor != ''
      @repuesto.valor = @nuevo_valor.to_f
    end
    @repuesto.save

    redirect_to @repuesto
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repuesto
      @repuesto = Repuesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repuesto_params
      params.require(:repuesto).permit(:codigo, :articulo, :familia, :panol, :taller, :movil1,
       :movil2, :stock, :stock_minimo, :valor)
    end
end

app/helpers/repuestos_helper.rb
module RepuestosHelper
end

app/views/repuestos/_form.html.erb
<div class="jumbotron">
  <%= bootstrap_form_with(model: repuesto, local: true) do |form| %>
    <% if repuesto.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(repuesto.errors.count, "error") %> prohibited this repuesto from being saved:</h2>

        <ul>
        <% repuesto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :codigo, label: "Código" %>
    </div>

    <div class="field">
      <%= form.text_field :articulo, label: "Artículo" %>
    </div>

    <div class="field">
      <%= form.text_field :panol, label: "Pañol" %>
    </div>

    <div class="field">
      <%= form.text_field :taller, label: "Taller" %>
    </div>

    <div class="field">
      <%= form.text_field :movil1, label: "Móvil 1" %>
    </div>

    <div class="field">
      <%= form.text_field :movil2, label: "Móvil 2" %>
    </div>

    <div class="field">
      <%= form.text_field :stock, label: "Stock" %>
    </div>

    <div class="field">
      <%= form.text_field :stock_minimo, label: "Stock mínimo" %>
    </div>

    <div class="field">
      <%= form.text_field :valor, label: "Valor", prepend: "$" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

<div class="jumbotron">
<h1>Importar Repuestos</h1>
  <%= form_tag import_repuestos_path, multipart: true do %>
    <%= file_field_tag :file, class: "btn" %>
    <%= submit_tag "Importar", class: "btn btn-lg btn-primary", id:"link-b" %>
  <% end %>
</div>

app/views/repuestos/index.html.erb
<h1>Repuestos</h1>

<%= search_form_for @q, html: { class: "form-inline" } do |f| %>
  <%= f.search_field :codigo_cont, placeholder: "Buscar repuesto...", class: "form-control" %>
<%end%>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Todos", repuestos_path(tipo: "todos") %>
  </li>
  <li class="nav-item">
    <%= link_to "Insumos", repuestos_path(tipo: "Insumo") %>
  </li>
  <li>
  <%= link_to "Lubricantes", repuestos_path(tipo: "Lubricante") %>
  </li>

  <li>
  <%= link_to "Neumáticos", repuestos_path(tipo: "Neumatico") %>
  </li>

  <li>
  <%= link_to "Pintura", repuestos_path(tipo: "Pintura") %>
  </li>

  <li>
  <%= link_to "Repuesto", repuestos_path(tipo: "Repuesto") %>
  </li>

  <li>
  <%= link_to "Seguridad", repuestos_path(tipo: "Seguridad") %>
  </li>

  <li>
  <%= link_to "Repuestos con bajo stock", repuestos_path(tipo: "Faltantes") %>
  </li>
</ul>

<div style="height:500px;overflow-y:scroll;;" class="jumbotron">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><center>Código</center></th>
        <th><center>Artículo</center></th>
        <th><center>Pañol</center></th>
        <th><center>Taller</center></th>
        <th><center>Móvil 1</center></th>
        <th><center>Móvil 2</center></th>
        <th><center>Stock</center></th>
        <th><center>Stock mínimo</center></th>
        <th><center>Valor</center></th>
        <th><center>Situación</center></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @repuestos.each do |repuesto| %>
        <tr>
          <td><center><%= repuesto.codigo %></center></td>
          <td><center><%= repuesto.articulo %></center></td>
          <td><center><%= repuesto.panol %></center></td>
          <td><center><%= repuesto.taller %></center></td>
          <td><center><%= repuesto.movil1 %></center></td>
          <td><center><%= repuesto.movil2 %></center></td>
          <td><center><%= repuesto.stock %></center></td>
          <td><center><%= repuesto.stock_minimo %></center></td>
          <td><center><%= number_to_currency(repuesto.valor, delimiter: ".", precision: 0) %></td>
          <% if repuesto.stock >= repuesto.stock_minimo %>
            <td><center><p class="text-success"> Bien</p></center></td>
          <% else %>
            <td><center><p class="text-danger"> Necesita repuesto</p></center></td>
          <%end%>
          <td><center><%= link_to 'Mostrar', repuesto %></center></td>
          <td><center><%= link_to 'Eliminar', repuesto, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="jumbotron">
  <center><%= link_to 'Nuevo Repuesto', new_repuesto_path, class: "btn btn-lg btn-primary", id:"link-b"  %></center>
</div>

<div class="jumbotron">
  <center><p><%= link_to "Ver Traspasos", traspasos_path, class: "btn btn-lg btn-primary" %> | <%= link_to 'Realizar Traspaso', new_traspaso_path, class: "btn btn-lg btn-primary" %></p></center>
</div>

<div class="jumbotron">
  <center><p><%= link_to "Ver Ajustes", ajustes_path, class: "btn btn-lg btn-primary" %> | <%= link_to 'Realizar Ajuste de Inventario', new_ajuste_path, class: "btn btn-lg btn-primary" %></p></center>
</div>

app/views/repuestos/new.html.erb
<h1>Nuevo Repuesto</h1>

<%= render 'form', repuesto: @repuesto %>

<%= link_to 'Volver', repuestos_path %>

app/views/repuestos/show.html.erb
<center><h1> Detalles repuesto</h1></center>

<div class="jumbotron">
  <table class="table">
    <tbody>
      <tr>
        <td><strong>Código:</strong></td>
        <td><%= @repuesto.codigo %></td>
      </tr>

      <tr>
        <td><strong>Artículo:</strong></td>
        <td><%= @repuesto.articulo %></td>
      </tr>

      <tr>
        <td><strong>Valor:</strong></td>
        <td><%= number_to_currency(@repuesto.valor, delimiter: ".", precision: 0)%></td>
      </tr>

      <tr>
        <td><strong>Stock mínimo:</strong></td>
        <td><%= @repuesto.stock_minimo %></td>
      </tr>

      <tr>
        <td><strong>Stock:</strong></td>
        <td><%= @repuesto.stock %></td>
      </tr>

      <tr>
        <td><strong>Pañol:</strong></td>
        <td><%= @repuesto.panol %></td>
      </tr>

      <tr>
        <td><strong>Taller:</strong></td>
        <td><%= @repuesto.taller %></td>
      </tr>

      <tr>
        <td><strong>Móvil 1:</strong></td>
        <td><%= @repuesto.movil1 %></td>
      </tr>

      <tr>
        <td><strong>Móvil 2:</strong></td>
        <td><%= @repuesto.movil2 %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="jumbotron">
  <center><h2>Actualizar atributos</h2></center>
  <%= form_tag repuesto_actualizar_atributos_path(@repuesto), multipart: true do %>
    <p> Nuevo stock mínimo: <%= number_field_tag :nuevo_stock_minimo, class: "btn" %></p>
    <p> Nuevo valor del repuesto: <%= number_field_tag :nuevo_valor, class: "btn" %></p>
    <%= submit_tag "Actualizar", class: "btn btn-lg btn-primary", id:"link-b" %>
  <% end %>
</div>


<%= link_to "Volver a Repuestos", repuestos_path %>
<br><br>

app/views/repuestos/traspaso.html.erb
<h1>Traspaso</h1>