config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'actualizar_valor_hh', to: 'orders#arreglar_valor_hh'

  get 'gruas/revisar_mantenciones', to: 'gruas#revisar_mantenciones',
   as: :revisar_mantenciones
  post 'gruas/analisis', to: 'gruas#analisis', as: :analisis

  get 'gruas/mantencion_realizada', to: 'gruas#mantencion_realizada', as: :mantencion_realizada

  post 'gruas/actualizar_hora_hombre', to: 'gruas#actualizar_hora_hombre', as: :actualizar_hora_hombre
  post 'gruas/horometros_iniciales', to: 'gruas#horometros_iniciales', as: :horometros_iniciales
  
  resources :ingresos do
    get 'cerrar', to: "ingresos#cerrar", as: :cerrar
    get 'completar', to: "ingresos#completar", as: :completar
  end

  resources :clientes do
    collection { post :import }
  end

  resources :repuestos do
    collection { post :import }
    post 'actualizar_atributos', to: 'repuestos#actualizar_atributos', as: :actualizar_atributos
  end
  
  resources :gruas do
    collection { post :import }
    post 'actualizar_horometro', to: 'gruas#actualizar_horometro', as: :actualizar_horometro
    post 'actualizar_cliente', to: 'gruas#actualizar_cliente', as: :actualizar_cliente
    post 'calcular_repuestos', to: 'gruas#calcular_repuestos', as: :calcular_repuestos
  	resources :orders
  end

  resources :suppliers do
  	collection { post :import }
  end

  resources :traspasos
  resources :ajustes

  #get 'importar', to: 'gruas#importar', as: :importar

  root "gruas#index"
end

app/models/grua.rb
class Grua < ApplicationRecord
	serialize :dicc_mantenciones
	has_many :orders

	require 'csv'

	def self.to_csv(options = {})
		column_names = %w{numero_serie cliente horometro secuencia horas_faltantes horas_teoricas}
		CSV.generate(options) do |csv|
		    csv << ['Numero interno', 'Cliente', 'Horometro', 'Secuencia', 'Horas faltantes', 'Horas teoricas']
		    all.each do |grua|
		      csv << grua.attributes.values_at(*column_names)
		    end
  		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: false) do |row|
			if row[16] == 'Si'
				asegurada = true
			else
				asegurada = false
			end

   		grua = Grua.create!(numero_serie: row[0].to_i, tipo: row[1], horometro: row[8].to_f,
   		lugar_actual: row[11], cliente: row[12], contrato: row[13], propietario: row[15], asegurada: asegurada, 
   		estado: row[17], marca: row[2], modelo: row[3], serie: row[4], motor: row[5], patente: row[6], ano: row[7].to_i, 
   		ton: row[9].to_i, mastil: row[10].to_f, observaciones: row[14])
   		grua.dicc_mantenciones = grua.set_dicc_mantenciones(grua.tipo, grua.horometro)
   		if grua.tipo == "Eléctrica"
   			grua.mantenciones = [6000, 2000, 1000, 250]
   		elsif grua.tipo == "Gas"
   			grua.mantenciones = [2800, 1400, 700, 350]
   		elsif grua.tipo == "Apilador"
   			grua.mantenciones = [2000, 1000, 500]
   		else grua.mantenciones = []
   		end

   		grua.save
      end
 	end

 	def self.importar_horometros_iniciales(file)
 		CSV.foreach(file.path, headers: false) do |row|
 			grua = Grua.find(row[0].to_i)
 			grua.horometro_inicial = row[1].to_f
 			grua.horometro = row[1].to_f
 			grua.dicc_mantenciones = grua.set_dicc_mantenciones(grua.tipo, grua.horometro - row[1].to_f)
 			grua.necesita, dicc = grua.evaluar_mantenciones(grua.horometro, grua.dicc_mantenciones, grua.mantenciones, grua.horometro_inicial)
		    if grua.necesita
		      grua.secuencia = dicc.keys()[0]
		      grua.horas_faltantes = dicc.values()[0][0]
		      grua.horas_teoricas = dicc.values()[0][1]
		    end
 			grua.save
 		end
 	end

 	def set_dicc_mantenciones(tipo, horometro)
 		dicc_default_gas = {350 => 0, 700 => 0, 1400 => 0, 2800 => 0}
 		dicc_default_electrica = {250 => 0, 1000 => 0, 2000 => 0, 6000 => 0}

 		# Evaluar hacerlo cada 50 hr
 		dicc_default_apilador = {500 => 0, 1000 => 0, 2000 => 0}

 		if tipo == 'Gas'
 			if horometro == 0
 				dicc = dicc_default_gas
 			else 
 				dicc = establecer_dicc(horometro, dicc_default_gas.keys)
 			end
 		elsif tipo == 'Eléctrica'
 			if horometro == 0
 				dicc = dicc_default_electrica
 			else 
 				dicc = establecer_dicc(horometro, dicc_default_electrica.keys)
 			end
 		elsif tipo == 'Apilador'
 			if horometro == 0
				dicc = dicc_default_apilador
			else
				dicc = establecer_dicc(horometro, dicc_default_apilador.keys)
			end
 		else dicc = {}
 		end
 		return dicc				
 	end

 	def establecer_dicc(horometro, lista_keys)
 		dicc = {}
 		lista_keys.each do |key|
 			valor = ((horometro - horometro%key)/key).to_i
 			if valor > 0
 				dicc[key] = valor
 			else
 				dicc[key] = 0
 			end
 		end
 		return dicc 
 	end

 	def evaluar_mantenciones(horometro, dicc_mantenciones, lista_mantenciones, hor_inicial)
 		"""
 		Devuelve siesque la grua necesita alguna mantencion y un diccionario con el valor
 		de la secuencia que se necesita mas una lista que contiene [cuanto le falta, 
 			horas teoricas a las que se le debe hacer]
 		"""
 		dicc_a_realizar = {}
 		# Para el caso de la grua a Gas esta lista seria = [2800, 1400, 700, 350]
 		# El caso de la 1050 podria ocurrir antes de 700
 		lista_mantenciones.each do |secuencia|

 			if secuencia.to_i == 700
 				# Vemos si es de 1050. Solo nos preocupamos de ver si es de 1050
 				# Si interfiere con una de 700 da lo mismo porque al apretar mantencion
 				# realizada esto se hara automatico
 				valor = (dicc_mantenciones[350] / 3).to_i
 				horas_para_mantencion = 1050 - ((horometro - horometro_inicial) - 1050*valor)
 				if horas_para_mantencion < 100
	 				dicc_a_realizar[1050] = [horas_para_mantencion, (horometro + horas_para_mantencion)]
	 				return true, dicc_a_realizar
	 			end
 			end

 			valor = dicc_mantenciones[secuencia.to_i]
 			horas_para_mantencion = secuencia.to_i - ((horometro - hor_inicial) - secuencia.to_i*valor)
 			
 			if horas_para_mantencion < 100
 				dicc_a_realizar[secuencia] = [horas_para_mantencion, (horometro + horas_para_mantencion)]
 				return true, dicc_a_realizar
 			end
 		end

 		return false, {}
 	end

 	def evaluar_mantenciones2(horometro, hor_inicial, mantenciones_elementales, tipo)
 		necesita = false
 		dicc_a_realizar = {}
 		if tipo == "Gas"
 			siguiente = 350*(mantenciones_elementales + 1) + hor_inicial
 			lista_secuencias = [2100, 1400, 1050, 350]
 		elsif tipo == "Apilador"
 			siguiente = 500*(mantenciones_elementales + 1) + hor_inicial
 			lista_secuencias = [2000, 1000, 500]
 		else
 			siguiente = 250*(mantenciones_elementales + 1) + hor_inicial
 			lista_secuencias = [6000, 2000, 1000, 250]
 		end

		faltante = siguiente - horometro
		if faltante <= 100
			lista_secuencias.each do |secuencia|
				if (siguiente - hor_inicial)%secuencia == 0
					necesita = true
					dicc_a_realizar[secuencia] = [faltante, siguiente]
				end
			end
		end 		
 		return necesita, dicc_a_realizar
 	end

 	def mantenciones_a_mostrar(tipo, hor_inicial, mantenciones_elementales)
 		x = mantenciones_elementales
 		if tipo == 'Gas'
	        n = hor_inicial + 350*x
	        prox_350 = n + 350
	        prox_1050 = n + 1050 - ((x%3)*350)
	        prox_1400 = n + 1400 - ((x%4)*350)
	        prox_2100 = n + 2100 - ((x%6)*350)
	        mantenciones_a_realizar = {350 => prox_350.to_i, 1050 => prox_1050.to_i, 
	          1400 => prox_1400.to_i, 2100 => prox_2100.to_i}

	    elsif tipo == "Apilador"
	    	n = hor_inicial + 500*x
	    	prox_500 = n + 500
	    	prox_1000 = n + 1000 - ((x%2)*500)
	    	prox_2000 = n + 2000 - ((x%4)*500)
	    	mantenciones_a_realizar = {500 => prox_500.to_i, 1000 => prox_1000.to_i, 
	    		2000 => prox_2000.to_i}

	    else
	        n = hor_inicial + 250*x
	        prox_250 = n + 250
	        prox_1000 = n + 1000 - ((x%4)*250)
	        prox_2000 = n + 2000 - ((x%8)*250)
	        prox_6000 = n + 6000 - ((x%24)*250)
	        mantenciones_a_realizar = {250 => prox_250.to_i, 1000 => prox_1000.to_i, 
	          2000 => prox_2000.to_i, 6000 => prox_6000.to_i}
	    end
	    return mantenciones_a_realizar
	end

 	def calcular_repuestos(fecha_inicial, fecha_final)
 		ordenes = self.orders.where(:fecha => fecha_inicial..fecha_final).order('fecha ASC')
 		total = 0
 		dicc_repuestos = {}
 		ordenes.each do |orden|
 			orden.repuestos_usados.each do |tupla|
 				if dicc_repuestos.keys.include?(tupla[0])
 					dicc_repuestos[tupla[0]] += tupla[1].to_f
 				else
 					dicc_repuestos[tupla[0]] = tupla[1].to_f
 				end
 			end
 			total += orden.total_repuestos
 		end
 		return dicc_repuestos, total, ordenes
 	end

 	def self.calcular_repuestos_totales(fecha_inicial, fecha_final)
 		dicc_repuestos = {}
 		total = 0
 		gruas = Grua.all
 		gruas.each do |grua|
 			dicc_grua = {}
 			ordenes = grua.orders.where(:fecha => fecha_inicial..fecha_final)
 			ordenes.each do |orden|
 				orden.repuestos_usados.each do |tupla|
					if dicc_repuestos.keys.include?(tupla[0])
 						dicc_repuestos[tupla[0]] += tupla[1].to_f
 					else
 						dicc_repuestos[tupla[0]] = tupla[1].to_f
 					end
 					total += orden.total
 				end
 			end
 		end
 		return dicc_repuestos, total
 	end


end

app/controllers/gruas_controller.rb
class GruasController < ApplicationController
  before_action :set_grua, only: [:show, :edit, :update, :destroy]

  # GET /gruas
  # GET /gruas.json
  def index
    #@gruas = Grua.where(["numero_serie = ?", params[:search].to_i])
    @gruas = Grua.all.order('numero_serie ASC')
    tipo = params[:tipo]
    if tipo == "Gas"
      @gruas = @gruas.where("tipo = 'Gas'").order('numero_serie ASC')
    elsif tipo == "Electricas"
      @gruas = @gruas.where("tipo = 'Eléctrica'").order('numero_serie ASC')
    elsif tipo == "Apiladores"
      @gruas = @gruas.where("tipo = 'Apilador'").order('numero_serie ASC')
    end
    @numero = params[:search]
    if @numero
      if @gruas.exists?(@numero)
        @gruas = [@gruas.find(@numero)]
      else
        @gruas = []
      end
    end
  end


  # GET /gruas/1
  def show
    if @grua.tipo == "Gas"
      elementales = @grua.dicc_mantenciones[350]
    elsif @grua.tipo == "Apilador"
      elementales = @grua.dicc_mantenciones[500]
    else
      elementales = @grua.dicc_mantenciones[250]
    end

    @necesita, @dicc = @grua.evaluar_mantenciones2(@grua.horometro, @grua.horometro_inicial,
     elementales, @grua.tipo)

    @mantenciones_a_realizar = @grua.mantenciones_a_mostrar(@grua.tipo, @grua.horometro_inicial,
     elementales)
    @orders = @grua.orders.order('fecha DESC')
  end

  # GET /gruas/new
  def new
    @grua = Grua.new
  end

  # GET /gruas/1/edit
  def edit
  end

  # POST /gruas
  # POST /gruas.json
  def create
    @grua = Grua.new(grua_params)
    @grua.dicc_mantenciones = @grua.set_dicc_mantenciones(@grua.tipo, @grua.horometro)

    if @grua.tipo == "Eléctrica"
        @grua.mantenciones = [6000, 2000, 1000, 250]
      elsif @grua.tipo == "Gas"
        @grua.mantenciones = [2800, 1400, 700, 350]
      elsif @grua.tipo == "Apilador"
        @grua.mantenciones = [2000, 1000, 500]
      else @grua.mantenciones = []
      end

    respond_to do |format|
      if @grua.save
        format.html { redirect_to @grua, notice: 'Grua creada exitosamente.' }
        format.json { render :show, status: :created, location: @grua }
      else
        format.html { render :new }
        format.json { render json: @grua.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gruas/1
  # PATCH/PUT /gruas/1.json
  def update
    respond_to do |format|
      if @grua.update(grua_params)
        format.html { redirect_to @grua, notice: 'Grua editada exitosamente.' }
        format.json { render :show, status: :ok, location: @grua }
      else
        format.html { render :edit }
        format.json { render json: @grua.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gruas/1
  # DELETE /gruas/1.json
  def destroy
    @grua.destroy
    respond_to do |format|
      format.html { redirect_to gruas_url, notice: 'Grua eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  def import
    Grua.import(params[:file])
    redirect_to root_url, notice: "Grua(s) importada(s)"
  end

  def actualizar_horometro
    @grua = Grua.find(params[:grua_id])
    @horometro_antiguo = @grua.horometro
    @hor = params[:nuevo_horometro].to_f
    @grua.horometro = @hor

    if @grua.tipo == "Gas"
      elementales = @grua.dicc_mantenciones[350]
    elsif @grua.tipo == "Apilador"
      elementales = @grua.dicc_mantenciones[500]
    else
      elementales = @grua.dicc_mantenciones[250]
    end

    if @hor >= @horometro_antiguo
      @necesita, @dicc = @grua.evaluar_mantenciones2(@hor, @grua.horometro_inicial, elementales,
        @grua.tipo)
      @grua.necesita = @necesita
      if @grua.necesita
        @grua.secuencia = @dicc.keys()[0]
        @grua.horas_faltantes = @dicc.values()[0][0]
        @grua.horas_teoricas = @dicc.values()[0][1]
      end
    end
    @grua.save
  end

  def actualizar_cliente
    @grua = Grua.find(params[:grua_id])
    if params[:cliente] != ''
      @grua.cliente = params[:cliente]
    end
    if params[:lugar] != ''
      @grua.lugar_actual = params[:lugar]
    end
    @grua.save
    redirect_to @grua
  end

  def calcular_repuestos
    @grua = Grua.find(params[:grua_id])
    @fecha_inicial = Date.new(params[:fecha_inicial].values[0].to_i,
                         params[:fecha_inicial].values[1].to_i,
                         params[:fecha_inicial].values[2].to_i)
    @fecha_final = Date.new(params[:fecha_final].values[0].to_i,
                         params[:fecha_final].values[1].to_i,
                         params[:fecha_final].values[2].to_i)
    @repuestos, @total_por_repuestos, @ordenes = @grua.calcular_repuestos(@fecha_inicial, @fecha_final)
    
    if @ordenes.length >= 2
      @hor_inicial = @ordenes[0].horometro
      @hor_final = @ordenes[-1].horometro
      @delta_hor = @hor_final - @hor_inicial
    end

  end

  def revisar_mantenciones
    @gruas = Grua.where(necesita: true).order(horas_faltantes: :asc)

    respond_to do |format|
      format.html
      format.csv { send_data @gruas.to_csv }
      format.xls { send_data @gruas.to_csv(col_sep: "\t") }
    end
  end

  def mantencion_realizada
    @grua = Grua.find(params[:grua_id])
    hor = @grua.horometro_inicial
    
    if @grua.tipo == "Gas"
      @grua.dicc_mantenciones[350] += 1
      elementales = @grua.dicc_mantenciones[350]
    elsif @grua.tipo == "Apilador"
      @grua.dicc_mantenciones[500] += 1
      elementales = @grua.dicc_mantenciones[500]
    else
      @grua.dicc_mantenciones[250] +=1
      elementales = @grua.dicc_mantenciones[250]
    end

    necesita, dicc = @grua.evaluar_mantenciones2(hor, @grua.horometro_inicial, elementales,
        @grua.tipo)
    @grua.necesita = necesita
    if @grua.necesita
      @grua.secuencia = dicc.keys()[0]
      @grua.horas_faltantes = dicc.values()[0][0]
      @grua.horas_teoricas = dicc.values()[0][1]
    end
    @grua.save

    redirect_back(fallback_location: root_path)
  end

  def analisis
    @gruas = Grua.all.order('numero_serie ASC')
    @fecha_inicial = Date.new(params[:fecha_inicial].values[0].to_i,
                         params[:fecha_inicial].values[1].to_i,
                         params[:fecha_inicial].values[2].to_i)
    @fecha_final = Date.new(params[:fecha_final].values[0].to_i,
                         params[:fecha_final].values[1].to_i,
                         params[:fecha_final].values[2].to_i)
    @repuestos, @total = Grua.calcular_repuestos_totales(@fecha_inicial, @fecha_final)
  end

  def actualizar_hora_hombre
    nuevo_valor = params[:nuevo_valor]
    hh = Otro.find(1)
    hh.valor = nuevo_valor
    hh.save
    redirect_to root_url
  end

  def horometros_iniciales
    Grua.importar_horometros_iniciales(params[:file])
    redirect_to root_url, notice: "Horometros iniciales seteados"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grua
      @grua = Grua.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grua_params
      params.require(:grua).permit(:tipo, :numero_serie, :horometro, :lugar_actual, :cliente, :contrato,
        :propietario, :asegurada, :estado, :marca, :modelo, :serie, :motor, :patente, :ano,
        :ton, :mastil, :observaciones, :dicc_mantenciones)
    end
end

app/helpers/gruas_helper.rb
module GruasHelper
end

app/views/gruas/edit.html.erb
<h1>Editar Grua</h1>

app/views/gruas/new.html.erb
<h1>Nueva Grua</h1>

<%= render 'form', grua: @grua %>

<%= link_to 'Volver', gruas_path %>
<br><br><br>

app/views/gruas/revisar_mantenciones.html.erb
<center><h1> Grúas que necesitan mantención </h1></center>
<br><br>

<p>
  Descargar:
  <%= link_to "Excel", revisar_mantenciones_path(format: "xls") %>
</p>

<table   class="table table-striped table-bordered table-sm">
	<thead>
		<th>Número de serie</th>
		<th>Cliente</th>
		<th>Horómetro</th>
		<th>Secuencia</th>
		<th>Horas faltantes</th>
		<th>Horas teóricas de mantención</th>
	</thead>
	<tbody>
		<% @gruas.each do |grua| %>

			<tr>
				<td><%= grua.numero_serie %></td>
				<td><%= grua.cliente %></td>
				<td><%= number_with_delimiter(grua.horometro.to_i, delimiter: ".") %></td>
				<td>Cada <%= grua.secuencia %> horas</td>
      			<% if grua.horas_faltantes <= 0 %>
        			<td class="text-danger"><%= number_with_delimiter(grua.horas_faltantes, delimiter: ".") %> horas</td>
      			<% else %>
        			<td class="text-primary"><%= number_with_delimiter(grua.horas_faltantes, delimiter: ".") %> horas</td>
      			<% end %>
      			<td><%= number_with_delimiter(grua.horas_teoricas.to_i, delimiter: ".") %> horas</td>
      			<td><%= link_to "Realizada", mantencion_realizada_path(grua_id: grua.id, secuencia: grua.secuencia) %></td>
			</tr>

		<% end %>
	</tbody>
	
</table>

app/views/gruas/show.html.erb
<center><h1>Grúa Num <%=@grua.numero_serie%></h1></center>
<center><h2>Horometro: <%= number_with_delimiter(@grua.horometro.to_i, delimiter: ".") %></h2></center>

<%= @grua.dicc_mantenciones %>

<% if @grua.necesita %>
  <div class="jumbotron">
    <center><h2 class="text-danger">Necesita mantención </h2></center>
    <br>
    <table class="table">
      <thead>
        <th>Secuencia</th>
        <th>Horas faltantes</th>
        <th>Horas teóricas de mantención</th>
      </thead>

      <tbody>
        <% @dicc.each do |key, value| %>
          <tr>
            <td>Cada <%= key %> horas</td>
            <% if value[0] <= 0 %>
              <td class="text-danger"><%= value[0] %> horas</td>
            <% else %>
              <td><%= value[0] %> horas</td>
            <% end %>
            <td><%= number_with_delimiter(value[1].to_i, delimiter: ".") %> horas</td>
            <td><%= link_to "Realizada", mantencion_realizada_path(grua_id: @grua.id, secuencia: @grua.secuencia) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
<% else %>
  <div class="jumbotron">
    <center><h2 class="text-success">Mantenciones al día</h2></center>
    <br>
    <table class="table">
      <thead>
        <th>Secuencia</th>
        <th>Próxima mantención</th>
      </thead>
      <tbody>
        <% @mantenciones_a_realizar.each do |secuencia, prox| %>
          <tr>
            <td>Cada <%=secuencia%> horas</td>
            <td><%= number_with_delimiter(prox, delimiter: ".") %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
<% end %>


<div class="jumbotron" style="height:500px;overflow-y:scroll;;">
  <center><h2 class="text-primary">Ordenes de Trabajo</h2></center>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Cliente</th>
        <th>Preventiva</th>
        <th>Estado máquina</th>
        <th>Equipo</th>
        <th> Total</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.fecha %></td>
          <td><%= order.cliente %></td>
          <% if order.preventiva %>
            <td>Sí</td>
          <% else %>
            <td>No</td>
          <% end %>
          <td><%= order.estado_maquina %></td>
          <td><%= order.equipo %></td>
          <td><%= number_to_currency(order.total, delimiter: ".", precision: 0) %></td>
          <td><%= link_to 'Mostrar', grua_order_path(grua_id: @grua, id: order) %></td>
          <td><%= link_to 'Eliminar', grua_order_path(grua_id: @grua, id: order), method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar la OT?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <br>

  <center><h2> Ingresar una nueva Orden de trabajo: </h2></center>
  <center><%= link_to "Nueva OT", new_grua_order_path(grua_id: @grua), class: "btn btn-lg btn-primary", id:"link-b" %></center>
  <br>
  <center><%= link_to "Ver hoja de vida", grua_orders_path(@grua) %></center>
</div>

<div class="jumbotron">
  <center><h2>Actualizar atributos</h2></center>
  <div class="row">
    <div class="col">
      <h3>Actualizar horómetro</h3>
      <%= form_tag grua_actualizar_horometro_path(@grua), multipart: true do %>
        <%= number_field_tag :nuevo_horometro, class: "btn" %>
        <%= submit_tag "Actualizar", class: "btn btn-lg btn-primary", id:"link-b" %>
      <% end %>
    </div>

    <p>---------------------------------------</p>

    <div class="col">
      <h3>Actualizar cliente y lugar</h3>
      <%= form_tag grua_actualizar_cliente_path(@grua), multipart: true do %>
        <h4>Cliente: <%= text_field_tag :cliente %></h4>
        <h4>Lugar: <%= text_field_tag :lugar %></h4>
        <%= submit_tag "Actualizar", class: "btn btn-lg btn-primary", id:"link-b" %>
      <% end %>
    </div>
  </div>
</div>

<div class="jumbotron">
  <center><h2>Análisis entre fechas</h2></center>
  <%= form_tag grua_calcular_repuestos_path(@grua), multipart: true do %>
    <div class="field">
      <p>Fecha inicial: <%= date_select :fecha_inicial, class: "btn" %></p>
    </div>
    <div class="field">
      <p>Fecha final: <%= date_select :fecha_final, class: "btn" %></p>
    </div>
    <%= submit_tag "Realizar análisis", class: "btn btn-lg btn-primary", id:"link-b" %>
  <% end %>
</div>


<div class="center jumbotron">
  <center><h2 class="text-primary"> Detalles Grúa</h2></center>
  <br>
  <nav>
    
    <table class="table">
      <tbody>
        <ul>
          <tr>
            <td><strong>Tipo:</strong></td>
            <td><%= @grua.tipo %></td>
          </tr>

          <tr>
            <td><strong>Horometro:</strong></td>
            <td><%= number_with_delimiter(@grua.horometro.to_i, delimiter: ".") %></td>
          </tr>

          <tr>
            <td><strong>Lugar Actual:</strong></td>
            <td><%= @grua.lugar_actual %></td>
          </tr>

          <tr>
            <td><strong>Cliente:</strong></td>
            <td><%= @grua.cliente %></td>
          </tr>

          <tr>
            <td><strong>Contrato:</strong></td>
            <td><%= @grua.contrato %></td>
          </tr>

          <tr>
            <td><strong>Propietario:</strong></td>
            <td><%= @grua.propietario %></td>
          </tr>

          <tr>
            <td><strong>Asegurada:</strong></td>
            <% if @grua.asegurada %>
              <td>Sí</td>
            <% else %>
              <td>No</td>
            <% end %>
          </tr>

          <tr>
            <td><strong>Estado:</strong></td>
            <td><%= @grua.estado %></td>
          </tr>

          <tr>
            <td><strong>Marca:</strong></td>
            <td><%= @grua.marca %></td>
          </tr>

          <tr>
            <td><strong>Modelo:</strong></td>
            <td><%= @grua.modelo %></td>
          </tr>

          <tr>
            <td><strong>Serie:</strong></td>
            <td><%= @grua.serie %></td>
          </tr>

          <tr>
            <td><strong>Motor:</strong></td>
            <td><%= @grua.motor %></td>
          </tr>

          <tr>
            <td><strong>Patente:</strong></td>
            <td><%= @grua.patente %></td>
          </tr>

          <tr>
            <td><strong>Ano:</strong></td>
            <td><%= @grua.ano %></td>
          </tr>

          <tr>
            <td><strong>Ton:</strong></td>
            <td><%= @grua.ton %></td>
          </tr>

          <tr>
            <td><strong>Mastil:</strong></td>
            <td><%= @grua.mastil %></td>
          </tr>

          <tr>
            <td><strong>Observaciones:</strong></td>
            <td><%= @grua.observaciones %></td>
          </tr>

          <tr>
            <td><strong>Horometro inicial:</strong></td>
            <td><%= number_with_delimiter(@grua.horometro_inicial.to_i, delimiter: ".") %></td>
          </tr>
        </ul>
      </tbody>
    </table>
  </nav>
</div>

<!%= link_to 'Editar', edit_grua_path(@grua) %>
<%= link_to 'Volver', gruas_path %>
<br>
<br>
<br>
<br>
<br>