config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'actualizar_valor_hh', to: 'orders#arreglar_valor_hh'

  get 'gruas/revisar_mantenciones', to: 'gruas#revisar_mantenciones',
   as: :revisar_mantenciones
  post 'gruas/analisis', to: 'gruas#analisis', as: :analisis

  get 'gruas/mantencion_realizada', to: 'gruas#mantencion_realizada', as: :mantencion_realizada

  post 'gruas/actualizar_hora_hombre', to: 'gruas#actualizar_hora_hombre', as: :actualizar_hora_hombre
  post 'gruas/horometros_iniciales', to: 'gruas#horometros_iniciales', as: :horometros_iniciales
  
  resources :ingresos do
    get 'cerrar', to: "ingresos#cerrar", as: :cerrar
    get 'completar', to: "ingresos#completar", as: :completar
  end

  resources :clientes do
    collection { post :import }
  end

  resources :repuestos do
    collection { post :import }
    post 'actualizar_atributos', to: 'repuestos#actualizar_atributos', as: :actualizar_atributos
  end
  
  resources :gruas do
    collection { post :import }
    post 'actualizar_horometro', to: 'gruas#actualizar_horometro', as: :actualizar_horometro
    post 'actualizar_cliente', to: 'gruas#actualizar_cliente', as: :actualizar_cliente
    post 'calcular_repuestos', to: 'gruas#calcular_repuestos', as: :calcular_repuestos
  	resources :orders
  end

  resources :suppliers do
  	collection { post :import }
  end

  resources :traspasos
  resources :ajustes

  #get 'importar', to: 'gruas#importar', as: :importar

  root "gruas#index"
end

app/models/ingreso.rb
class Ingreso < ApplicationRecord

	validates :proveedor, :presence => true

	def self.format(dicc)
		correcto = true
		falta = false
		lista_a_devolver = []
		lista_faltante = []
		lista_errores = []
		lista_atributos = dicc["repuestos"]
		lista_atributos.each do |diccionario|
			lista = []
			faltante = []
			a = diccionario["repuesto"]["codigo"]
			if a != ''
				if self.chequear_codigo(a)
					lista.append(a)
					lista.append(diccionario["repuesto"]["cantidad"])
					lista.append(diccionario["repuesto"]["precio"])
					lista_a_devolver.append(lista)
					if diccionario["repuesto"]["faltante"] != ''
						falta = true
						faltante = [a, diccionario["repuesto"]["faltante"]]
						lista_faltante.append(faltante)
					end
				else
					correcto = false 
					lista_errores.append(a)
				end
			end
		end
		if correcto
			return correcto, lista_a_devolver, falta, lista_faltante
		else
			return correcto, lista_errores, falta, lista_faltante
		end
	end

	def self.chequear_codigo(a)
		return Repuesto.exists?(codigo: a)
	end

	def self.agregar_faltantes(repuestos, repuestos_faltantes)
		repuestos_faltantes.each do |faltante|
			repuestos.each do |repuesto|
				if faltante[0] == repuesto[0]
					repuesto[1] = (repuesto[1].to_f + faltante[1].to_f).to_s
				end
			end
		end
		return repuestos
	end
end

app/controllers/ingresos_controller.rb
class IngresosController < ApplicationController
  before_action :set_ingreso, only: [:show, :edit, :update, :destroy]

  # GET /ingresos
  # GET /ingresos.json
  def index
    @ingresos = Ingreso.all.order('fecha DESC')
  end

  # GET /ingresos/1
  # GET /ingresos/1.json
  def show
  end

  # GET /ingresos/new
  def new
    @ingreso = Ingreso.new
  end

  # GET /ingresos/1/edit
  def edit
  end

  # POST /ingresos
  # POST /ingresos.json
  def create
    # Se ve siesque estan correctos los input
    correcto, lista_repuestos, falta, lista_faltante = Ingreso.format(params[:repuestos])
    
    if correcto
      @ingreso = Ingreso.new(ingreso_params)
      @ingreso.repuestos = lista_repuestos


      # Aca se agregan al inventario y se calcula el total agregado
      @ingreso.total = Repuesto.agregar(lista_repuestos)
      
      # Si es que hay faltante
      if falta
        @ingreso.abierta = true # Se deja abierta la OC
        @ingreso.repuestos_faltantes = lista_faltante
      end

      respond_to do |format|
        if @ingreso.save
          format.html { redirect_to @ingreso, notice: 'Ingreso creado exitosamente.' }
          format.json { render :show, status: :created, location: @ingreso }
        else
          format.html { render :new }
          format.json { render json: @ingreso.errors, status: :unprocessable_entity }
        end
      end
    else
      @errores = lista_repuestos
    end
  end

  # DELETE /ingresos/1
  # DELETE /ingresos/1.json
  def destroy
    @ingreso.destroy
    respond_to do |format|
      format.html { redirect_to ingresos_url, notice: 'Ingreso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def completar
    @ingreso = Ingreso.find(params[:ingreso_id])
    total_agregado = Repuesto.agregar_faltantes(@ingreso.repuestos_faltantes)
    @ingreso.repuestos = Ingreso.agregar_faltantes(@ingreso.repuestos, @ingreso.repuestos_faltantes)
    @ingreso.total += total_agregado
    @ingreso.abierta = false
    @ingreso.repuestos_faltantes = []
    @ingreso.save
    redirect_to ingresos_url
  end

  def cerrar
    @ingreso = Ingreso.find(params[:ingreso_id])
    @ingreso.abierta = false
    @ingreso.repuestos_faltantes = []
    @ingreso.save
    redirect_to ingresos_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingreso
      @ingreso = Ingreso.find(params[:id])
    end

    def ingreso_params
      params.require(:ingreso).permit(:proveedor, :total, :fecha, :numero_factura,
       :orden_compra)
    end
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/views/ingresos/_form.html.erb
<%= bootstrap_form_with(model: ingreso, local: true) do |form| %>
  <% if ingreso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingreso.errors.count, "error") %> prohibited this ingreso from being saved:</h2>

      <ul>
      <% ingreso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% proveedores = [''] %>
  <% Supplier.all.each do |p| %>
    <% proveedores.append(p.nombre) %>
  <%end%>

  <div class="field">
    <%= form.select(:proveedor, proveedores, {}, { :class => 'my_style_class' })%>
  </div>

  <div class="field">
    <%= form.number_field :numero_factura, label: "Número de factura" %>
  </div>

  <div class="field">
    <%= form.number_field :orden_compra, label: "Orden de Compra" %>
  </div>

  <div class="field">
    <%= form.date_select :fecha %>
  </div>

  <div class="jumbotron">
    <table>
      <thead>
        <tr>
          <th><center>Código de repuesto</center></th>
          <th><center>Cantidad</center></th>
          <th><center>Precio por unidad</center></th>
          <th><center>Faltante</center></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= text_field_tag "repuestos[repuestos][]repuesto[codigo]" %></td>
          <td><%= number_field_tag "repuestos[repuestos][]repuesto[cantidad]" %></td>
          <td><%= number_field_tag "repuestos[repuestos][]repuesto[precio]" %></td>
          <td><%= number_field_tag "repuestos[repuestos][]repuesto[faltante]" %></td>

        </tr>

        <% contador = 10 %>
        <% while contador > 0 %>
          <tr>
            <td><input type="text" name="repuestos[repuestos][]repuesto[codigo]"></td>
            <td><input type="number" name="repuestos[repuestos][]repuesto[cantidad]"></td>
            <td><input type="number" name="repuestos[repuestos][]repuesto[precio]"></td>
            <td><input type="number" name="repuestos[repuestos][]repuesto[faltante]"></td>
          </tr>
          <% contador -= 1 %>
        <%end%>
      </tbody>
    </table>
  </div>


  <div class="field">
    <%= form.submit "Crear Ingreso", class: "btn btn-lg btn-primary", id:"link-b"%>
  </div>
<% end %>

app/views/ingresos/create.html.erb
<h1> No existen los repuestos con los siguientes códigos:</h1>

<% @errores.each do |error| %>
	<div>
		<h4> - <%= error.to_i %> </h4>
	</div>
<% end %>

<h2> Por favor, vuelva atrás y corriga dichos códigos</h2>

app/views/ingresos/index.html.erb
<center><h1>Ingresos</h1></center>
<br><br>


<div style="height:500px;overflow-y:scroll;;">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Proveedor</th>
        <th>Numero de factura</th>
        <th>Numero OC</th>
        <th>Fecha</th>
        <th>Total por recibido</th>
        <th>Estado</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @ingresos.each do |ingreso| %>
        <tr>
          <td><%= ingreso.proveedor %></td>
          <td><%= ingreso.numero_factura %></td>
          <td><%= ingreso.orden_compra %></td>
          <td><%= ingreso.fecha %></td>
          <td><%= number_to_currency(ingreso.total, delimiter: ".", precision: 0) %></td>
          <% if ingreso.abierta %>
            <td class="text-danger">Abierta</td>
          <% else %>
            <td class="text-success">Cerrada</td>
          <% end %>
          <td><%= link_to 'Detalles', ingreso %></td>
          <td><%= link_to 'Borrar', ingreso, method: :delete, data: { confirm: 'Seguro que quieres borrar el ingreso?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="jumbotron">
  <center><%= link_to 'Nuevo Ingreso', new_ingreso_path, class: "btn btn-lg btn-primary", id:"link-b" %></center>
</div>

app/views/ingresos/new.html.erb
<h1>Nuevo Ingreso</h1>

<%= render 'form', ingreso: @ingreso %>

<br>

<%= link_to 'Volver', ingresos_path %>
<br><br><br>

app/views/ingresos/show.html.erb
<h1><center> Detalles Ingreso</center> </h2>
<br>

<div class="jumbotron">
	<table class="table">
		<tbody>
			<tr>
				<td><strong>Proveedor:</strong></td>
				<td><%=@ingreso.proveedor%></td>
			</tr>

			<tr>
				<td><strong>Numero Factura:</strong></td>
				<td><%= @ingreso.numero_factura %></td>
			</tr>

			<tr>
				<td><strong>Numero Orden de Compra:</strong></td>
				<td><%= @ingreso.orden_compra %></td>
			</tr>

			<tr>
				<td><strong>Fecha:</strong></td>
				<td><%= @ingreso.fecha %></td>
			</tr>


		</tbody>
		
	</table>
</div>


<h1 class="text-primary">Elementos agregados:</h1>
<div class="jumbotron">
  <table class="table">
	  <thead>
	    <tr>
	      <th>Repuesto</th>
	      <th>Cantidad</th>
	      <th>Precio unitario</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @ingreso.repuestos.each do |tupla| %>
	    	<% r = Repuesto.find_by(codigo: tupla[0]) %>
	    	<% nombre = r.articulo %>
	    	<% valor = r.valor %>
	      <tr>
	        <td><%= nombre %></td>
	        <td><%= tupla[1].to_f %></td>
	        <td><%= number_to_currency(valor, delimiter: ".", precision: 0) %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<br>

	<h3>Total por elementos agregados: <strong><%= number_to_currency(@ingreso.total, delimiter: ".", precision: 0)%></strong></h3>
</div>

<% if @ingreso.abierta %>
	
	<h1 class="text-primary">Elementos Faltantes:</h1>
	<div class="jumbotron">
	  <table class="table">
		  <thead>
		    <tr>
		      <th>Repuesto</th>
		      <th>Cantidad faltante</th>
		      <th>Precio Unitario</th>
		    </tr>
		  </thead>

		  <tbody>
		  	<% total_faltante = 0 %>
		    <% @ingreso.repuestos_faltantes.each do |tupla| %>
		    	<% r = Repuesto.find_by(codigo: tupla[0]) %>
	    		<% nombre = r.articulo %>
	    		<% valor = r.valor %>
	    		<% total_faltante += tupla[1].to_f*valor %>
		      <tr>
		        <td><%= nombre %></td>
		        <td><%= tupla[1].to_f %></td>
		        <td><%= number_to_currency(valor, delimiter: ".", precision: 0) %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		<h3>Total por elementos faltantes: <strong><%= number_to_currency(total_faltante, delimiter: ".", precision: 0)%></strong></h3>
	</div>
	
	<div class="jumbotron">
		<%= link_to 'Completar Orden de Compra', ingreso_completar_path(@ingreso), class: "btn btn-lg btn-primary", id:"link-b" %>
		<%= link_to 'Cerrar Orden de Compra', ingreso_cerrar_path(@ingreso.id), class: "btn btn-lg btn-primary", id:"link-b" %>
	</div>

<%end%>

<%= link_to "Volver a ingresos", ingresos_path, class: "btn btn-lg btn-primary" %>
<br><br><br>