config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'actualizar_valor_hh', to: 'orders#arreglar_valor_hh'

  get 'gruas/revisar_mantenciones', to: 'gruas#revisar_mantenciones',
   as: :revisar_mantenciones
  post 'gruas/analisis', to: 'gruas#analisis', as: :analisis

  get 'gruas/mantencion_realizada', to: 'gruas#mantencion_realizada', as: :mantencion_realizada

  post 'gruas/actualizar_hora_hombre', to: 'gruas#actualizar_hora_hombre', as: :actualizar_hora_hombre
  post 'gruas/horometros_iniciales', to: 'gruas#horometros_iniciales', as: :horometros_iniciales
  
  resources :ingresos do
    get 'cerrar', to: "ingresos#cerrar", as: :cerrar
    get 'completar', to: "ingresos#completar", as: :completar
  end

  resources :clientes do
    collection { post :import }
  end

  resources :repuestos do
    collection { post :import }
    post 'actualizar_atributos', to: 'repuestos#actualizar_atributos', as: :actualizar_atributos
  end
  
  resources :gruas do
    collection { post :import }
    post 'actualizar_horometro', to: 'gruas#actualizar_horometro', as: :actualizar_horometro
    post 'actualizar_cliente', to: 'gruas#actualizar_cliente', as: :actualizar_cliente
    post 'calcular_repuestos', to: 'gruas#calcular_repuestos', as: :calcular_repuestos
  	resources :orders
  end

  resources :suppliers do
  	collection { post :import }
  end

  resources :traspasos
  resources :ajustes

  #get 'importar', to: 'gruas#importar', as: :importar

  root "gruas#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lift Service</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div class="navbar-left">
              <%= link_to "Grúas", root_url, class: 'btn btn-lg', id: "logo" %>
              <%= link_to "Repuestos", repuestos_path, class: 'btn btn-lg' %>
              <%= link_to "Ingresos", ingresos_path, class: 'btn btn-lg' %>
              <%= link_to "Proveedores", suppliers_path, class: 'btn btn-lg' %>
              <%= link_to "Clientes", clientes_path, class: 'btn btn-lg' %>
            </div>
          <% end %>
        <% end %>
        <div class="navbar-right">
          <% if user_signed_in? %>
            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: 'btn btn-lg' %>
          <% else %>
            <%= link_to "Iniciar Sesión", new_user_session_path, class: 'btn btn-lg' %><%= link_to "Registrarte", new_user_registration_path, class: 'btn btn-lg' %>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="container">
      <p class="text-success"><%= notice %></p>
      <p class="alert"><%= alert %></p>


      <% if current_page?(new_user_session_path) or current_page?(new_user_registration_path) %>
        <%= yield %>
      <% end %>



      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= yield %>
        <% else %>
          <h2>Debes ser administrador para participar</h2>
        <% end %>
      <% end %>
    </div>
  </body>
</html>